### ISSUE TITLE
Spicetify Theme not Working

### ISSUE THREAD

**Issue by yaakuub** [pradyungn/Mountain#10]
I have put the "spicetify" directory from the "Mountain-master" directory into /home/user/.config/spicetify/Themes/ and enabled it in the config-xpui.ini file. The default spicetify theme works, but the mountain theme simply leaves spotify as default.

OS: Arch

**Comment by pradyungn** [comment]
Hmmmm that's odd... Normally i enable the theme using the spicetify cli, not the file directly. Also, the theme broke with the last Spotify update, so that might be it?

**Comment by pradyungn** [comment]
Spicetify theme is definitely deprecated. Gonna need to redo this sometime.
