### ISSUE TITLE
Wrong colors for emacs.

### ISSUE THREAD

**Issue by crzjp** [pradyungn/Mountain#11]
I use doom-themes packages in my own config for Emacs:

```emacs-lisp
(use-package doom-themes
    :defer 1
    :init
    (setq
     doom-themes-enable-bold t
     doom-themes-enable-italic t)
    :config
    (add-to-list 'custom-theme-load-path "~/.emacs.d/themes")
    (load-theme 'doom-mountain t)
    (doom-themes-visual-bell-config)
    (doom-themes-org-config))
```

but i'm getting this look, that for me is a bit weird: http://0x0.st/-dU3.png

**Comment by CG-GeisT** [comment]
Also having this problem in my doom-emacs config

**Comment by pradyungn** [comment]
I'm so sorry for the late response! Truth be told, the doom emacs theme is especially jank - it's the dracula theme swapped in with colors willy nilly if my memory serves me right. Meant to serve as a temporary stopgap, but there ended up never being a "proper" theme developed :/

**Comment by pradyungn** [comment]
Almost a year later, I finally spent time to get this working _properly_.

**Comment by crzjp** [comment]
Wow, I didn't even remember opening this issue and I didn't receive an alert to 22's messages. Anyway, I know you are a common human like me and spend the day doing other several things and don't always have time to certain others, still I thank you for the efforts to port this beautiful colorscheme!

**Comment by pradyungn** [comment]
Of course :) it helps that I finally found time to start working on my own emacs configuration. I think basic org-mode support just got pushed. Hoping to crank out some other stuff soon!
