### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by 0hAodha** [pradyungn/Mountain#17]
I noticed that there is no license attached to this colourscheme. It would be good to add a license, proprietary or otherwise, just so users of this theme know where they stand legally. 

If you would like to make this colourscheme free to use, I would recommend the MIT License which is the license used by other popular colourschemes such as Dracula & Gruvbox.

**Comment by pradyungn** [comment]
So sorry about the late response - college is a timesink of epic proportions. I've added an MIT license per your recommendation.
