### ISSUE TITLE
Not working for neovim 

### ISSUE THREAD

**Issue by fagundescodes** [pradyungn/Mountain#19]
Is anyone else facing the same issue? I'm unable to use the theme with lazy loading in the following manner:

{
"mountain-theme/nvim",
},

**Comment by pradyungn** [comment]
Odd - personally, I've been using the vim plugin in my own Neovim configuration, as follows:

```
Plug 'pradyungn/Mountain', { 'rtp': 'vim' }
```

Hopefully that works - if not, I wouldn't be surprised. The neovim theme was a project that never really fully got finished. I'm contemplating removing it from the megarepo as a result.
