### ISSUE TITLE
Firefox Theme

### ISSUE THREAD

**Issue by dimspith** [pradyungn/Mountain#3]
Hello, first of all thanks for making this, I found it perfect for system-wide usage so i made a firefox theme using your color palette. I made sure to credit you in the theme summary and link to this github page. I'd like for it to be added to the README if possible. Any suggestions or fixes on the design are welcome!

If you prefer distribution by an `xpi` file and/or want me to remove it from the firefox store just mention it.

Link: https://addons.mozilla.org/en-US/firefox/addon/mountain_theme/

**Comment by pradyungn** [comment]
Hey, this looks awesome! I'd love to put the.xpi file in the repo, so feel free to add a PR for that :) Within the PR you submit, I'd prefer for you to follow the format I use for all the other themes, and then make a README inside of the subfolder with a small description about your theme. This isn't really an ISSUE per se, so I'm gonna close it, but I'm looking forward to distributing your theme!
