### ISSUE TITLE
[Enhancement] Adding HEX Value tables to docs

### ISSUE THREAD

**Issue by iSparsh** [pradyungn/Mountain#6]
I've been using the Mountain theme in a few of my projects and after deciding to scrap Aquarium I've decided to contribute to this theme. Only problem I've encountered as far as I've reached is not being able to access the HEX codes for the colors on the repo. I have to go to alacritty.yml to copy colors from there and that's been, lets say not good-going.

It would be nice if we had one HTML or md file with all hex codes in one place. That would make it easy to copy the colors.
I am ready to make a PR for this. I only need you to require the file format you need for this file.

**Comment by FrenzyExists** [comment]
:thinking: I was doing a theme with the exact same name, `Aquarium` wait, hold up, mish is that you?

**Comment by iSparsh** [comment]
yeah thats me

**Comment by pradyungn** [comment]
hex codes should be in the MD files linked in the main README (Fuji/Hotaka) - or did you want to have a table other than that?

**Comment by iSparsh** [comment]
Nope, Markdown! Thanks for the info. I'll make a PR soon!
